### ISSUE TITLE
Compile error on a WEMOS D1 card

### ISSUE THREAD

**Issue by jmcamado** [anmaped/esp8266-scheduler#2]
Hi
I'm getting a compiler error (SchedulerBlink) when trying to compile for the card WEMOS D1, any idea? 
Error below->

Arduino: 1.8.3 (Windows 7), Board: "WeMos D1 R2 & mini, 160 MHz, 921600, 4M (3M SPIFFS)"

Archiving built core (caching) in: C:\Users\ejoaama\AppData\Local\Temp\arduino_cache_626985\core\core_esp8266_esp8266_d1_mini_CpuFrequency_160,UploadSpeed_921600,FlashSize_4M3M_150480f6e5d0f0a0ebbc80e344daee88.a
C:\Users\ejoaama\AppData\Local\Temp\arduino_build_169311/arduino.ar(core_esp8266_wiring.c.o): In function `delay':

C:\Users\ejoaama\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/core_esp8266_wiring.c:42: multiple definition of `delay'

libraries\esp8266-scheduler\Scheduler.cpp.o:C:\Users\ejoaama\Documents\Arduino\libraries\esp8266-scheduler/Scheduler.cpp:96: first defined here

C:\Users\ejoaama\AppData\Local\Temp\arduino_build_169311/arduino.ar(core_esp8266_main.cpp.o): In function `esp_yield':

C:\Users\ejoaama\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/core_esp8266_main.cpp:82: multiple definition of `esp_yield'

libraries\esp8266-scheduler\Scheduler.cpp.o:C:\Users\ejoaama\Documents\Arduino\libraries\esp8266-scheduler/Scheduler.cpp:89: first defined here

C:\Users\ejoaama\AppData\Local\Temp\arduino_build_169311/arduino.ar(core_esp8266_main.cpp.o): In function `optimistic_yield':

C:\Users\ejoaama\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/core_esp8266_main.cpp:104: multiple definition of `optimistic_yield'

libraries\esp8266-scheduler\Scheduler.cpp.o:C:\Users\ejoaama\Documents\Arduino\libraries\esp8266-scheduler/Scheduler.cpp:93: first defined here

libraries\esp8266-scheduler\Scheduler.cpp.o:(.text._ZN14SchedulerClass5yieldEv+0x4): undefined reference to `setjmp'

libraries\esp8266-scheduler\Scheduler.cpp.o:(.text._ZN14SchedulerClass5yieldEv+0x8): undefined reference to `longjmp'

libraries\esp8266-scheduler\Scheduler.cpp.o: In function `SchedulerClass::yield()':

Scheduler.cpp:(.text._ZN14SchedulerClass5yieldEv+0x18): undefined reference to `setjmp'

Scheduler.cpp:(.text._ZN14SchedulerClass5yieldEv+0x2e): undefined reference to `longjmp'

libraries\esp8266-scheduler\Scheduler.cpp.o: In function `SchedulerClass::init(void (*)(), void (*)(), unsigned char const*)':

Scheduler.cpp:(.text._ZN14SchedulerClass4initEPFvvES1_PKh+0x1f): undefined reference to `setjmp'

collect2.exe: error: ld returned 1 exit status

Multiple libraries were found for "Scheduler.h"
 Used: C:\Users\ejoaama\Documents\Arduino\libraries\esp8266-scheduler
 Not used: C:\Users\ejoaama\Documents\Arduino\libraries\os48
exit status 1
Error compiling for board WeMos D1 R2 & mini.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by anmaped** [comment]
Duplicated https://github.com/anmaped/esp8266-scheduler/issues/1.
