### ISSUE TITLE
Compile error for NodeMCU

### ISSUE THREAD

**Issue by HugoSH** [anmaped/esp8266-scheduler#4]
Hardware: NodeMCU 1.0
CPU Frequency: 80 MHz
Flash Size: 4M/1M 
SDK: esp8266 for Arduino 2.3.0

Example code: ScheduleBlink
Compile error:
arduino.ar(core_esp8266_wiring.c.o): In function `delay':
/Users/Hugo/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/core_esp8266_wiring.c:42: multiple definition of `delay'
libraries/esp8266-scheduler-master/Scheduler.cpp.o:/Users/hugo/Documents/Arduino/libraries/esp8266-scheduler-master/Scheduler.cpp:96: first defined here
arduino.ar(core_esp8266_main.cpp.o): In function `esp_yield':
/Users/hugo/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/core_esp8266_main.cpp:82: multiple definition of `esp_yield'
libraries/esp8266-scheduler-master/Scheduler.cpp.o:/Users/hugo/Documents/Arduino/libraries/esp8266-scheduler-master/Scheduler.cpp:89: first defined here
arduino.ar(core_esp8266_main.cpp.o): In function `optimistic_yield':
/Users/hugo/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/core_esp8266_main.cpp:104: multiple definition of `optimistic_yield'
libraries/esp8266-scheduler-master/Scheduler.cpp.o:/Users/hugo/Documents/Arduino/libraries/esp8266-scheduler-master/Scheduler.cpp:93: first defined here
libraries/esp8266-scheduler-master/Scheduler.cpp.o:(.text._ZN14SchedulerClass5yieldEv+0x4): undefined reference to `setjmp'
libraries/esp8266-scheduler-master/Scheduler.cpp.o:(.text._ZN14SchedulerClass5yieldEv+0x8): undefined reference to `longjmp'
libraries/esp8266-scheduler-master/Scheduler.cpp.o: In function `SchedulerClass::yield()':
Scheduler.cpp:(.text._ZN14SchedulerClass5yieldEv+0x18): undefined reference to `setjmp'
Scheduler.cpp:(.text._ZN14SchedulerClass5yieldEv+0x2e): undefined reference to `longjmp'
libraries/esp8266-scheduler-master/Scheduler.cpp.o: In function `SchedulerClass::init(void (*)(), void (*)(), unsigned char const*)':
Scheduler.cpp:(.text._ZN14SchedulerClass4initEPFvvES1_PKh+0x1f): undefined reference to `setjmp'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by anmaped** [comment]
Duplicated https://github.com/anmaped/esp8266-scheduler/issues/1.
